#$ docker run --hostname atomix1 --name atomix-1
# --ip 172.20.0.2 --network network-ffm -itd sdnprojekt/atomix:1.0.0 
version: '2.4'

services:
 atomix_1:
  image: atomix/atomix:3.1.12
  container_name: atomix-1
  networks:
   network-ffm:
    ipv4_address: 172.20.0.2
  #entrypoint: /bin/bash
  stdin_open: true # docker run -i
  tty: true #docker run -t
  
 atomix_2:
  image: atomix/atomix:3.1.12
  container_name: atomix-2
  networks:
   network-ffm:
    ipv4_address: 172.20.0.3
  #entrypoint: /bin/bash
  stdin_open: true # docker run -i
  tty: true #docker run -t
  
 onos1:
  image: onosproject/onos:2.7.0
  container_name: onos1
  networks:
   network-ffm:
    ipv4_address: 172.20.0.4
  #entrypoint: /bin/bash
  stdin_open: true # docker run -i
  tty: true #docker run -t

 onos2:
  image: onosproject/onos:2.7.0
  container_name: onos2
  networks:
   network-ffm:
    ipv4_address: 172.20.0.5
  #entrypoint: /bin/bash
  stdin_open: true # docker run -i
  tty: true #docker run -t
#volumes:
# volume-ffm:

networks:
 network-ffm:
  driver: bridge
  driver_opts:
   com.docker.network.bridge.name: network-ffm
  ipam:
   config:
    -
      subnet: 172.20.0.0/23
      gateway: 172.20.0.1
